# config-repo/booking-service.yml
spring:
  application:
    name: booking-service

server:
  port: 10257

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/aiot02_team2
    username: aiot02_team2
    password: m/NWS@3y-8)UZ2Zo
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  data:
    web:
      pageable:
        one-indexed-parameters: true